### ISSUE TITLE
Probleme de version avec mod Inactifs

### ISSUE THREAD

**Issue by Roms0406** [OGSteam/mod-autoupdate#21]
Lors de la mise à jour du mod Inactifs de l'ancienne version 1.0.8 vers la nouvelle 1.0.10
La mise à jour se déroule correctement mais au retour sur le tableau de mise à jour la version installée reste en 1.0.8 et propose de maj vers 1.0.10

En désinstallant le mod et en le réinstallant directement, la bonne version (1.0.10) est bien prise en compte

**Comment by darknoon29** [comment]
Bug OGSpy 😙

**Comment by machine62** [comment]
elle est facile celle la ...

**Comment by Roms0406** [comment]
je trouve aussi ^^

**Comment by darknoon29** [comment]
Je vais essayer de corriger dans OGSpy assez vite 😉 je l'avais déjà vu il y a un long moment

**Comment by machine62** [comment]
j'ai ouvert un ticket sur ogspy ....
