### ISSUE TITLE
Impossible de télécharger mods

### ISSUE THREAD

**Issue by cfz42** [OGSteam/mod-autoupdate#23]
Sur une installation fraîche d'OGS (3.3.4) avec mod-autoupdate 3.1.0, je ne vois aucuns mods disponibles pour installation.

Peut être est-ce normal, mais je m'attendais à ce que l'extension tape sur une sorte de repository qui centralise tous les mods disponibles.

Dois-je donc installer chacun de mes mods manuellement ?

**Comment by darknoon29** [comment]
Hello,
L'extension attaque directement l'API de Github. Ce ne serait pas un module php qui manquerait ? Il faudrait vérifier les logs php pour confirmer.

**Comment by cfz42** [comment]
Bon c'est assez incompréhensible mais le mod fonctionne correctement désormais.

Peut être suis-je tombé sur un problème avec l'API Github.

Merci pour la réponse rapide, je ferme.

**Comment by darknoon29** [comment]
Oui probablement un petit soucis avec l'api. Bonne nouvelle que ce soit revenu.
